Api criada
Caio-Machado/onboarding_environment pull request #3
Opened 2021-12-03 18:10 UTC by Caio-Machado

Rotas criadas e funcionando.

2021-12-03 18:49 UTC, ArthurFreitas requested changes

2021-12-03 18:49 UTC, ArthurFreitas commented on rails/app/apirest/Gemfile
> +gem 'sass-rails', '~> 4.0.0'
Remover gemas desnecessárias

2021-12-03 18:49 UTC, ArthurFreitas commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +gem install rubocop
Acho que foi sem querer esse gem install aqui

2021-12-03 18:49 UTC, ArthurFreitas commented on rails/app/apirest/config/routes.rb
> +  get 'show/:id', to: 'apicruds#show'
É melhor usar a keyword `resources` que cria as rotas de acordo com a convenção: https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions

Caso não queira criar todas as rotas que o resource cria, é possível usar `except` com uma lista de symbols.

2021-12-03 18:49 UTC, ArthurFreitas commented on rails/app/apirest/app/views/apicruds/show.html.erb
> +<p id="notice"><%= notice %></p>
Como o desafio pede por uma API REST, não precisa renderizar nenhuma página html no retornos das actions

2021-12-03 18:49 UTC, ArthurFreitas commented on rails/app/apirest/test/controllers/apicruds_controller_test.rb
> +require 'test_helper'
Teste não precisa no primeiro desafio. Pode deixar o arquivo, porém não iremos revisar nesse momento.

2021-12-03 18:49 UTC, ArthurFreitas commented on rails/README.md
> +## Routes
Quando mutar o router para resources, vai precisar mudar a documentação das rotas.

2021-12-03 18:57 UTC, NoahCamargo requested changes

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/models/apicrud.rb
> +  field :sku, type: String
Adicione um espaço entre o include e o field

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/models/apicrud.rb
> +class Apicrud
O modelo representa o objeto em questão e um elemento no banco. No caso como estamos cadastrando produtos, o nome mais adequado seria `Product`, o que criaria no banco a tabela `products`

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/config/routes.rb
> +  #   end
Remova os comentários

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/config/routes.rb
> +  delete 'delete/:id', to: 'apicruds#destroy'
Existe um convenção conhecida como RESTFUL que nos ajuda a normalizar e trabalhar da melhor forma com requisições HTTP. Nesse caso, não seria necessário dizer no path `create`, para saber que estamos criando algo, nem `delete` e `show`.

Segundo a ideia de RESTFUL os endpoints ficariam da seguinte maneira:

```
GET /products/:id
POST /products
PUT /products/:id
DELETE /products/:id
```
Dessa forma podemos aproveitar mais dos vermos http e sabemos exatamente o que estamos criando ou deletando

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +class ApicrudsController < ApplicationController
Aqui no caso, seria o controller de products. Onde iremos executar as ações de produtos e dessa forma, fica até mais fácil de integras com o resources do routes.rb e dessa forma podemos aproveitar a ideia de RESTFUL

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +  before_action :set_apicrud, only: [:show, :edit, :update, :destroy]
Deve ficar melhor com `except: %i[create index]`

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +    end
As funções são alinhadas ao private. Tente seguir o [style guide](https://github.com/rubocop/ruby-style-guide)

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +    end
No rails em geral e nesse caso não é necessário validar o formato, principalmente em tipos primitivos, pois ele fara automaticamente o cast para o formato que esta especificado no modelo

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +    if verify[0]
Como comentado abaixo, essa parte do `verify_params`, não é necessária

2021-12-03 18:57 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/apicruds_controller.rb
> +          format.json { render action: 'show', status: :created }
```
    "id": {
        "$oid": "61aa66767027bb00b2000002"
    },
```

Ao invés de retornar assim, faça retornar assim `"id": "61aa66767027bb00b2000002"`

2021-12-06 18:01 UTC, NoahCamargo requested changes

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/products_controller.rb
> +
Remover espaço extra

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/products_controller.rb
> +
Remover espaço e adicionar entre a linha 7 e 8

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/products_controller.rb
> +  end
Uma solução que não necessitaria esse if seria a seguinte:

```
  def index
    products = Product.all

    render json: view_context.index_json(products)
  end
```

A variável `@products`, não tem necessidade de esta no escopo de classe, então poderia ser uma variável local

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/products_controller.rb
> +  end
No else, é mais interessante informar qual erro aconteceu. Ele pode ser obtido atraves de `@product.errors`

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/app/helpers/products_helper.rb
> +  end
Não entendi a necessidade do parse. Poderia ser assim, não?

```
  def show_json(product)
    {
      id: product.id.to_s,
      sku: product.sku,
      nome: product.name,
      description: product.description,
      amount: product.amount,
      price: product.price
    }
  end
```

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/app/helpers/products_helper.rb
> +end
Uma alternativa quando deseja rodar a lista modificando seu valor é utilizar o `map`

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/config/mongoid.yml
> +
Normalmente não tem enters em .yml

2021-12-06 18:01 UTC, NoahCamargo commented on rails/app/apirest/tmp/pids/server.pid
> +43
Pode adicionar o pid ao git ignore

2021-12-07 12:22 UTC, NoahCamargo approved these changes

2021-12-07 12:22 UTC, NoahCamargo commented on rails/app/apirest/app/controllers/products_controller.rb
> +      render json: { 'menssage' => @product.errors }
No geral é mais interessante usar como atom `message:`

2021-12-07 12:22 UTC, NoahCamargo commented on rails/app/apirest/app/helpers/products_helper.rb
> +    json_to_render = { id: product['_id'].to_s,
Pode remover essa variável também

2021-12-07 12:22 UTC, NoahCamargo commented on rails/app/apirest/log/development.log
> +
É bom remover o arquivo de log adicionando no git ignore

2021-12-09 12:51 UTC, merged