Entrega-1
Caio-Machado/onboarding_environment pull request #4
Opened 2021-12-09 14:37 UTC by Caio-Machado

Rotas criadas e funcionando, conexão com o mesmo banco de dados do desafio 1 funcionando.

2021-12-09 16:03 UTC, NoahCamargo requested changes

2021-12-09 16:03 UTC, NoahCamargo commented on phoenix/README.md
> +	"products": {
O certo seria `product`, já que é um produto que esta sendo passado

2021-12-09 16:03 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/application.ex
> +
Esse espaço extra não tem

2021-12-09 16:03 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/management.ex
> +
Esse espaço não tem

2021-12-09 16:03 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/management/products.ex
> +
Espaço extra

2021-12-09 16:03 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +      |> put_resp_header("location", Routes.products_path(conn, :show, products))
Não entendo a necessidade de um redirect aqui (`location`, é um `header` usado em redirects)

2021-12-09 16:03 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/views/products_view.ex
> +    %{data: render_one(products, ProductsView, "products.json")}
Se entra um `product`, deveria sair um `product`

2021-12-10 15:40 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/router.ex
> +  scope "/api", ApiProductsWeb do
Usar as mesmas rotas do desafio anterior.

2021-12-10 15:40 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    with {:ok, %Products{} = products} <- Management.create_products(products_params) do
Trocar os withs com apenas um generator para outra estrutura de controle (ex: case), ou adicionar outro generator nele.

2021-12-10 15:40 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    products = Management.get_products!(id)
usar singular onde tem `products` mas só está usando um `product`

2021-12-10 15:40 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    products = Management.get_products!(id)
show, update, delete, create, Management, etc.

2021-12-10 15:40 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/management/products.ex
> +  schema "products" do
Precisa corresponder a collection do primeiro desafio

2021-12-14 17:55 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/management.ex
> +  def get_product!(id), do: Repo.get(Products, id)
Se usa ! no final quando a função levanta uma exception (https://hexdocs.pm/elixir/main/naming-conventions.html#trailing-bang-foo). Nesse caso não é necessário.

2021-12-14 17:55 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/management.ex
> +  def list_myapp_development do
`list_products` é um nome melhor para essa função.

2021-12-14 17:55 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +      {:ok, _} -> conn
Roda um `mix format` nesse arquivo

2021-12-14 18:12 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/views/products_view.ex
> +    render_one(result, ChangesetView, "error.json")
Nesse caso é melhor chamar o render pro changesetView diretamente no controller, ou retornar a tupla `{:error, %Ecto.Changeset{}}` que vai cair no fallbackController e ser renderizado corretamente.

2021-12-14 18:12 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/management.ex
> +  def change_product(%Products{} = product, attrs \\ %{}) do
Essa função é código morto (não é chamado em lugar algum), pode deletar.

2021-12-14 18:12 UTC, NoahCamargo requested changes

2021-12-14 18:12 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/management.ex
> +  alias ApiProducts.Management.Products
Tente unir chamas iguais e separar chamadas diferentes

```
import Ecto.Query, warn: false

alias ApiProducts.Repo
alias ApiProducts.Management.Products
```

2021-12-14 18:12 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    case {_, result} = Management.create_product(product_params) do
No uso correto do case, ficaria no seguinte formato

```
case Management.create_product(product_params) do
  {:ok, result} -> ...
  {_, result} -> render(conn, "error.json", product: result)
end
```

Acredito que a ideia usando o `match` no `case` era reaproveitar o `result`, porem dessa forma foge do style guide da linguagem e o match para o erro não garante que venha um result

2021-12-14 18:12 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    end
Essa parte de carregar o product  e retornar not_found se não encontrado, pode ser reaproveitado com um `plug`, que funciona parecido com o `before_action`

2021-12-14 18:12 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +      nil -> json(conn, %{"error" => "Product not found!"})
Aproveite mais dos verbos e status HTTP retornando o status 404 que já nos diz que não foi encontrado sem a necessidade de uma mensagem pra isso

2021-12-14 18:12 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +  end
O que acontece se der errado no update e delete? No update se tiver erro de validação ele retornara um chageset com os erros que deveria ser retornado

2021-12-14 18:17 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    case {_, result} = Management.create_product(product_params) do
Para deixar o FallbackController tratando do erro de validação, poderia ficar assim:

```
case Management.create_product(product_params) do 
  {:ok, result} -> ...
  error -> error
end
```

2021-12-14 18:19 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +      _ -> json(conn, %{"menssage" => alter_data(product)})
typo em "menssage"

2021-12-14 18:19 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    end
O Plug pode te ajudar a diminuir a duplicação de código entre os metodos: show, update, delete.

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +      {:error, result} ->
Como tu só ta repassando o {:error, result} tu pode substituir por só:

`error -> error`

aqui e nos outros métodos.

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +  defp product_exists?(conn, _) do
Por convenção, usar "?" no final de um nome de função indica que ela retorna um boolean, https://hexdocs.pm/elixir/main/naming-conventions.html. Nesse caso tu pode renomear para `fetch_product`, ou `assign_product`.

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    case conn.params["id"] |> Management.get_product() |> Management.update_product(product_params) do
O produto já está disponível em `conn.assigns[:product]`, não precisa buscar no banco novamente.

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +    case conn.params["id"] |> Management.get_product() |> Management.update_product(product_params) do
Mesma coisa no delete

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/config/dev.exs
> +  http: [port: 3000],
Trocar para port: 4000, a aplicação phoenix está sendo exposta no 4000 pelo docker-compose.

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +  def show(conn, %{"id" => id}) do
Não precisa dar match com a var id aqui, dá uma olhada nos warnings ao rodar o projeto.

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/views/products_view.ex
> +  alias ApiProductsWeb.ChangesetView
Esse alias não é utilizado, remover

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +        |> render(:"404")
faltou um halt/1 aqui para impedir o pipeline de seguir para a action no caso de produto não encontrado.

```
 conn
  |> put_status(:not_found)
  |> put_view(ApiProductsWeb.ErrorView)
  |> render(:"404")
  |> halt()
```

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/products_controller.ex
> +      {:ok, _} -> json(conn, %{:ok => "The product with id #{conn.params["id"]} has updated!"})
Aqui (e no delete) retornar um 204 é suficiente, se quiser manter a resposta pode alterar o formato para:

`json(conn, %{message: "The product with id #{conn.params["id"]} has updated!"})`

atualmente está um pouco estranha:
```
{
    "ok": "The product with id 61bb52e87200b501ca035e8f has been updated!"
}
```

2021-12-16 15:04 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/fallback_controller.ex
> +  def call(conn, {:error, :not_found}) do
Esse match nunca ocorre, pode remover

2021-12-16 18:50 UTC, ArthurFreitas approved these changes

2021-12-17 13:49 UTC, merged