Add redis on show and elastic on index
Caio-Machado/onboarding_environment pull request #6
Opened 2022-01-10 17:37 UTC by Caio-Machado

The redis was used in the show endpoint, to storage every product has been shown.
The "elastic" was used in the index endpoint, to storage the products and used for filter the search.

2022-01-10 19:53 UTC, NoahCamargo requested changes

2022-01-10 19:53 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +    with %{} <- ElasticService.filter_search(params) do
Se vier vazio não vai vir no padrão com status code?

2022-01-10 19:53 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +
Espaço extra

2022-01-10 19:53 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +
espaço extra

2022-01-10 19:53 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +
extra

2022-01-10 19:53 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +      ElasticService.add_product(product)
Faltou setar no redis

2022-01-11 13:24 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/plugs/get_product_plug.ex
> +
Linha a mais

2022-01-11 13:24 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/plugs/get_product_plug.ex
> +
Linha a mais

2022-01-11 13:24 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/services/elastic_service.ex
> +
Linha a mais

2022-01-11 13:24 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/services/elastic_service.ex
> +    case Enum.empty?(params) do
Um case com somente true e false é um if.
Nesse caso em específico, como o params é quem dita o comportamento da função, faz mais sentido usar pattern match criando dois filter_search, um com params vazio e outro normal.

2022-01-11 13:24 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/services/elastic_service.ex
> +        verify_result(get("products/product/_search?q=" <> string_params))
Quando multiplos parênteses se concatenam assim, é um sinal de que o operador |> pode ser usado pra facilitar a leitura

2022-01-11 13:24 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/services/elastic_service.ex
> +
Linha a mais

2022-01-11 18:06 UTC, NoahCamargo approved these changes

2022-01-11 18:12 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/services/elastic_service.ex
> +    if params[param] != nil do
Aqui é possível criar um terceiro modify_param com params sendo nil, isso removeria o if dos dois métodos modify_param

2022-01-12 13:03 UTC, merged