Desafio 4
Caio-Machado/onboarding_environment pull request #7
Opened 2022-01-18 18:14 UTC by Caio-Machado

2022-01-24 17:30 UTC, NoahCamargo requested changes

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/management/products.ex
> +    |> validate_required([:sku, :name, :description, :amount, :price, :bar_code])
Utilize barcode, tudo junto

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +    confirm_param({:ok, true}, "sku", params["sku"])
Como esta usando pipeline, a primeira função tambem deve estar no formato de pipeline. [Style Guide](https://github.com/christopheradams/elixir_style_guide#bare-variables)

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +    if String.length(value) >= 8 && String.length(value) <= 10 do
No desafio pede entre 8 e 13, não?

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +  defp validate_parameters(params) do
Suas validações estão corretas, mas nesse caso, tente usar validações através do changeset

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/management_test.exs
> +  test "list_products/0 with stored products" do
Como esta repetindo `list_products/0`, `get_product/1`, etc, utilize  o describe

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/management_test.exs
> +  def create_product_test() do
Utilize setup

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/services/elastic_service_test.exs
> +    assert {:ok, result} = ElasticService.filter_search(@filter_search_valid)
Como não esta usando "result", utilize _ como prefixo

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/services/elastic_service_test.exs
> +defmodule ApiProducts.ElasticServiceTest do
Faça testes validando o result

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +    assert {:error, :bad_request, _menssage} = ProductsService.create(@create_invalid_params)
Verifique se a mensagem é a esperada

2022-01-24 17:30 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +  test "create/1 with invalid sku, price and bar_code paramters" do
Utilize o describe

2022-01-24 18:09 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +    with {:ok, true} <- validate_parameters(product_params),
Os parametros só estão sendo validados no create e não no update. Se tu mover as validações para o próprio changeset feito Noah falou, não precisa se preocupar com isso.

2022-01-24 18:10 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/fallback_controller.ex
> +  def call(conn, {:error, :bad_request, menssage}) do
Type em message

2022-01-24 18:13 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert [] != Management.list_products()
Valide se o produto foi listado corretamente

2022-01-24 18:13 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert %{} = Management.get_product(create_product_test().id)
Valide se o produto retornado é o correto

2022-01-24 18:13 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert {:ok, %{}} = Management.create_product(@valid_attrs)
Valide se o produto foi criado corretamente

2022-01-24 18:13 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert {:error, _} = Management.create_product(@invalid_attrs)
Valide o erro retornado

2022-01-24 18:13 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert {:ok, %{}} = Management.update_product(create_product_test(), @new_valid_attrs)
Valide se o produto foi atualizado corretamente

2022-01-24 18:14 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert {:error, _} = Management.update_product(create_product_test(), @invalid_attrs)
Valida a mensagem de erro

2022-01-24 18:14 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/management_test.exs
> +    assert {:ok, %{}} = Management.delete_product(create_product_test())
Valida se o produto não está no banco mais

2022-01-24 18:23 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/elastic_service_test.exs
> +    with_mock ElasticService, [add_product: fn(_product) -> {:ok, 201, %{}} end] do
Os testes com mock desse modulo não estão verificando o comportamento do teu código. O objetivo do mock é simular o comportamento de uma dependência. Exemplo: a função f do Modulo A chama add_product de ElasticService, no teste da função f tu iria mockar ElasticService.add_product e verificar se ela foi chamada com os argumentos corretos (e não verificar se o retorno da função é o que tu mockou).

2022-01-24 18:29 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +    assert {:error, _error} = ProductsService.create(@create_blank_params)
Um teste verificando cada validação: "price is less than zero", "sku has invalid characters", etc.

2022-02-10 12:29 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/elastic_service_test.exs
> +      ElasticService.filter_search(valid_filters)
Faltou o assert

2022-02-10 12:29 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/elastic_service_test.exs
> +      assert {:ok, nil} == ElasticService.filter_search(%{})
Nesse caso não deveria retornar todos?

2022-02-10 12:30 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +      ElasticService.delete_all()
delete_all apaga o indice ou todos os produtos nele? Se for o indice inteiro esse teste não é necessário.

2022-02-10 12:32 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/redis_service_test.exs
> +    test "Stores a product in the redis" do
Nome do teste está errado

2022-02-10 12:32 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/redis_service_test.exs
> +    test "Stores a product in the redi", %{product: product} do
get_product armazena produto no redis?

2022-02-10 12:59 UTC, NoahCamargo requested changes

2022-02-10 12:59 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +        assert {:ok, product} == ProductsService.list(list_valid)
O resultado tambem deveria ser uma lista de produtos, não?

2022-02-10 18:45 UTC, phrodrigues commented on phoenix/app/api_products/lib/api_products/services/elastic_service.ex
> +  defp join_param(string_params), do: "#{get_link()}#{get_index()}_search?q=#{string_params}"
O formato #{get_link()}#{get_index()} ficou muito estranho, usado e repetido multiplas vezes. Não é um erro em si, é um sinal que um método poderia ser criado pra agrupar as chamadas, algo como "link_with_index" ou algo do tipo

2022-02-10 19:53 UTC, NoahCamargo approved these changes

2022-02-11 15:16 UTC, ArthurFreitas approved these changes

2022-02-11 15:19 UTC, merged