Desafio 5
Caio-Machado/onboarding_environment pull request #8
Opened 2022-02-22 15:05 UTC by Caio-Machado

2022-02-22 17:11 UTC, NoahCamargo requested changes

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products_web/controllers/report_controller.ex
> +      error -> send_resp(conn, 500, "")
Como as duas condições tem uma linha, seguindo o [style guide](https://github.com/christopheradams/elixir_style_guide), aqui elas deveriam estar juntas

```
  case ReportJob.enqueue(%{"report" => "report"}) do
    :ok -> send_resp(conn, 204, "")
    error -> send_resp(conn, 500, "")
  end
```

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/jobs/report_job.ex
> +  def perform(%{"report" => "report"}) do
Esse %{"report" => "report"} ta meio estranho aqui

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/jobs/report_job.ex
> +    File.write(ReportService.get_path(), encoded)
Aqui ele recebe uma lista mesmo? O espera uma string?

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +        |> Enum.map(fn p -> Map.delete(p, :__struct__) end)
Acho que o Map.from_struct/0, remove essas chaves, tente fazer um teste

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/jobs/report_job_test.exs
> +      Management.delete_all()
Seria melhor adicionar um truncate no DataCase

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/jobs/report_job_test.exs
> +      assert result == content
Embora os resultados sejam iguais, o CSV gerado pode estar em um formato não esperado. Nesse caso, é bom adicionar um fixture e comparar o csv gerado com o fixture

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products/services/report_service_test.exs
> +  test "generate_csv/1", %{product: product, generated_csv: generated_csv} do
É bom escrever algo, como "retorna linhas do csv encodado", algo assim

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products_web/controllers/report_controller_test.exs
> +      Management.delete_all()
Adicionando o truncate, esse delete seria automático

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products_web/controllers/report_controller_test.exs
> +      Management.create_product(new_product)
Adicione isso a um setup

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products_web/controllers/report_controller_test.exs
> +      conn = get(conn, Routes.report_path(conn, :update_report))
Seria post, correto?

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products_web/controllers/report_controller_test.exs
> +      assert result == conn.resp_body
Não faz sentido ler o arquivo e comparar o response. Já que o response de sucesso no update_report é 204 (No Content)

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products_web/controllers/report_controller_test.exs
> +      Management.create_product(new_product)
Passe isso para um setup

2022-02-22 17:11 UTC, NoahCamargo commented on phoenix/app/api_products/test/api_products_web/controllers/report_controller_test.exs
> +      assert result == conn.resp_body
É bom tambem verificar com um fixture se o arquivo esta da forma correta

2022-02-22 19:50 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/jobs/report_job.ex
> +  require Logger
Esse require foi usado para algo?

2022-02-22 19:59 UTC, ArthurFreitas commented on phoenix/app/api_products/config/config.exs
> +    queues: [[name: "normal", jobs: :default]]
que tal "reports" como nome da fila

2022-02-22 20:05 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/jobs/report_job_test.exs
> +      {:ok, products} = ProductsService.list(%{})
Esse resultado não é utilizado para nada

2022-02-22 20:06 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/jobs/report_job.ex
> +  def perform(%{"report" => "report"}) do
Poderia substituir para %{"type"=>"products"}

2022-02-22 20:10 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products/jobs/report_job.ex
> +    :ok
Pode remover esse :ok e usar o File.write! no lugar, dessa forma o job será retentado caso o File.write falhe.

2022-02-22 20:15 UTC, ArthurFreitas commented on phoenix/app/api_products/lib/api_products_web/controllers/report_controller.ex
> +      :ok -> send_resp(conn, 204, "")
Aqui o correto é 202 Accepted

2022-02-22 20:16 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +    result = %{
Se é constante deveria estar no setup_all, um nome melhor seria expected_product

2022-02-22 20:17 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/report_service_test.exs
> +  test "generate_csv/1", %{product: product, generated_csv: generated_csv} do
Testar os border cases nil e lista vazia

2022-02-22 20:18 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/jobs/report_job_test.exs
> +    test "Write a product to the file", %{new_product: new_product} do
Testar o border case quando não tem produtos

2022-03-02 18:49 UTC, leoribeiro36 commented on phoenix/app/api_products/lib/api_products/services/products_service.ex
> +    |> Enum.map(fn p -> Map.delete(p, :__meta__) end)
O mais indicado é colocar um nome mais intuitivo para as variáveis, por mais que dê para entender que "p" corresponde ao produto, é melhor que seja escrito "product" para tornar a leitura do código mais fluída.

2022-03-02 18:57 UTC, leoribeiro36 commented on phoenix/app/api_products/test/api_products/jobs/report_job_test.exs
> +      "amount,barcode,description,id,name,price,sku\r\n50,123456789,Description,6216692d77161b03291e1f4c,Name,10.0,Sku\r\n"
Não tá errado, mas ficaria melhor se fosse criada uma pasta que agrupe arquivos de csv que seriam utilizados para o teste, ai seria só fazer a substituição dessa string por algo próximo a isso:
expected_report = load_csv("./meu_path/csv_de_teste.csv")

2022-03-02 19:05 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/services/products_service_test.exs
> +      get_product: expected_product
expected_product: expected_product

2022-03-02 19:17 UTC, ArthurFreitas approved these changes
Para mim ta ok, espera mais alguem revisar e dá o merge.

2022-03-03 18:02 UTC, ArthurFreitas commented on phoenix/app/api_products/test/api_products/fixtures/fixtures.ex
> +  def get_fixture(fixture) do
aqui tu pode retornar só o conteúdo do arquivo, no lugar da tupla {:ok, content}

2022-03-03 18:59 UTC, ArthurFreitas approved these changes

2022-03-03 19:00 UTC, merged